version: '3.8'

services:
  app:
    build: .
    ports:
      - '${SERVER_PORT:-8080}:8080'
    env_file:
      - .env
    restart: always
    depends_on:
      - pgvector

  pgvector:
    image: 'pgvector/pgvector:pg16'
    environment:
      - POSTGRES_DB=spring
      - POSTGRES_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - POSTGRES_USER=${SPRING_DATASOURCE_USERNAME}
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pgdata: